In [2]:
[1, 2, 2] * 3

[1, 2, 2, 1, 2, 2, 1, 2, 2]

# Numerical Python (Numpy)

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
a * 3

array([3, 6, 9])

# Math Functions

In [19]:
np.sum(a)

{1, 2, 3}

In [22]:
np.pi

3.141592653589793

In [23]:
np.sin(np.pi)

1.2246467991473532e-16

In [24]:
np.degrees(np.pi)

180.0

# arange, linspace, logspace

In [26]:
range(5)

range(0, 5)

In [27]:
np.arange(0, 5, .5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [28]:
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

In [29]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Reshape

In [43]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

In [44]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [45]:
a.shape

(2, 6)

In [46]:
a.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [49]:
a.reshape(3, -4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
a.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
a.reshape(-1, 5)

ValueError: cannot reshape array of size 12 into shape (5)

# to Row & to Column

In [54]:
a.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [56]:
a.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Random Number Generator (RNG) 

In [58]:
np.random.rand(3, 2)

array([[0.54813363, 0.76109446],
       [0.43353977, 0.64810745],
       [0.01757854, 0.65942714]])

In [62]:
np.random.randn(3)

array([ 0.1892403 ,  0.14044409, -1.51167585])

# Controlled Randamness

In [69]:
state = np.random.RandomState(1)
state.rand(3)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04])

In [73]:
state = np.random.RandomState(42)
state.randint(2, 10, 12)

array([8, 5, 6, 8, 4, 9, 6, 6, 8, 3, 4, 8])